version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:1.5.5
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1885"
    ports:
      - "1885:1883"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    volumes:
      - ./data/zk/data:/var/lib/zookeeper/data
      - ./data/zk/log:/var/lib/zookeeper/log
    env_file:
      - ./zookeeper.env
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file:
      - ./kafka.env
  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    depends_on:
      - kafka
    env_file:
      - ./kafka.env
  kafka-connect:
    build:
      context: ./kafka_connect_mqtt/
      dockerfile: Dockerfile
    image: kafka_connect:v1
    hostname: kafka-connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: '/usr/share/java,/etc/kafka-connect/jars'
      CONNECT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/jars:/etc/kafka-connect/jars
    depends_on:
      - zookeeper
      - kafka
      - mosquitto
  clickhouse:
    build:
      context: ./clickhouse/
      dockerfile: Dockerfile
    image: clickhouse:v1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 18123:8123
      - 19000:9000
    volumes:
      - /home/obrol/clickhouse/src/persistent/data:/var/lib/clickhouse/
      - /home/obrol/clickhouse/src/persistent/logs:/var/log/clickhouse-server/
